require('kfr2')
fmt = kfr2.audio_format()
wav = kfr2.wav_load('BabyElephantWalk60.wav',fmt)
zpk = kfr2.iir_lowpass(kfr2.bessel(12),300.0,fmt.samplerate)
bqs = kfr2.to_sos(zpk)
print(zpk.k)
print(bqs[1].a0,bqs[1].a1,bqs[1].a2,bqs[1].b0,bqs[1].b1,bqs[1].b2)
output = kfr2.biquad_filter(bqs)
output:apply(wav)
kfr2.wav_save(wav,"test.wav",fmt.channels, fmt.samplerate)
