language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    packages:
      - autoconf-archive
      - autopoint
      - dssi-dev
      - intltool
      - libasound-dev
      - libgtk2.0-dev
      - libjack-jackd2-dev
      - liblash-compat-dev
      - liblo-dev
      - pandoc

jobs:
  include:
    - os: linux
      dist: trusty
      name: "Build (Ubuntu Trusty 14.04 / GCC 4.8.4)"
      compiler: gcc
      script: ./autogen.sh && ./configure && make V=1 distcheck && make V=1 check
