#pragma once

#include "Envelopes.hpp"
#include "AudioTK.hpp"
#include "JoonasFX.hpp"
#include "ReissFX.hpp"
#include "Amplifiers.hpp"
#include "Oscillators.hpp"
#include "Delays.hpp"
#include "FiltersFX.hpp"
#include "HammerFX.hpp"
#include "Dynamics.hpp"
#include "FxDSP.hpp"

#include "Bezier.hpp"
#include "BezierDistortion.hpp"
#include "spline.h"

#include "FaustFX.hpp"
#include "LV2Plugin.hpp"

#include "BodeShifter.hpp"
#include "Stereofiyer.hpp"
#include "KocMocPhasor.hpp"
#include "Phasor.hpp"
#include "FXCE2Chorus.hpp"
#include "FXChorus.hpp"
#include "FXChorus2.hpp"
#include "FXChorusDelay.hpp"
#include "FXDelays.hpp"
#include "FXDistortion.hpp"
#include "FXDynamics.hpp"
#include "FXFFTSpectrum.hpp"
#include "FXFilters.hpp"
#include "FXFirFilters.hpp"
#include "FXFlanger.hpp"
#include "FXFreeVerb3.hpp"
#include "FXFverb.hpp"
#include "FXLeslie.hpp"
#include "FXLimiterDsp.hpp"
#include "FXObjects.hpp"
#include "FXOscillators.hpp"
#include "FXOutputLimiter.hpp"
#include "FXPhaseVocoders.hpp"
#include "FXProcessor.hpp"
#include "FXProcessors.hpp"
#include "FXPsola.hpp"
#include "FXReverbs.hpp"
#include "FXRoboVerb.hpp"
#include "FXSampleRate.hpp"
#include "FXWaveDigitalFilters.hpp"
#include "FXYKChorus.hpp"
#include "TSClipper.hpp"
#include "TSTone.hpp"

#include "Rubberband.hpp"

#include "ScaledMapParam.hpp"

#include "WaveguideLibrary.hpp"

