#pragma once

//#include "FX/HammerFX.cpp"
#include "FX/HammerFX.hpp"
#include "FX/HammerFXAutoWah.hpp"
#include "FX/HammerFXChorus.hpp"
#include "FX/HammerFXDelay.hpp"
#include "FX/HammerFXDistortion.hpp"
#include "FX/HammerFXEcho.hpp"
#include "FX/HammerFXPhaser.hpp"
#include "FX/HammerFXPitch.hpp"
#include "FX/HammerFXRotary.hpp"
#include "FX/HammerFXSustain.hpp"
#include "FX/HammerFXTremolo.hpp"
#include "FX/HammerFXTubeAmp.hpp"
#include "FX/HammerFXVibrato.hpp"
